# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://yannischen.cn
date_format: "ordinal"
title: 'Yannis的个人博客'
subtitle: "Yannis的个人博客..."
description: 'Yannis的个人博客，专注于平时遇到问题的整理及总结。可能是他人的源码，可能有自己的感悟及灵机一动。不求上天入地，只求兵来将挡水来土掩。'
keywords: Yannis, YannisChen, 后端, 后端开发, 后端博客, javascript, vuejs, Java, Python
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yannis
organization: yannischen.cn
organization_url: https://yannischen.cn/
github_username: pigga
location: Beijing, China
email: piggachen@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 知识库

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title.html
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: pigga/pigga.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: yannis
# https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: matrixseven
#     repo: blog-comments
#     oauth:
#         client_id: 833bda0353417cc694b0
#         client_secret: 8a3e24a7889cfb4cdf4382ccc81237f6d2885e9d
# https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: yannis
#     repo: blog-comments
#     clientID: d7178707fa8f7738c3cc
#     clientSecret: 0fbcb4b43443cd81a516ab8b3f2782ebd311d214
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-128171891-3
